/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import com.ReSys.dao.NhanVienDAO;
import com.ReSys.utis.Auth;
import com.ReSys.utis.MsgBox;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author HI
 */
public class ChangePassForm extends javax.swing.JPanel {

    NhanVienDAO dao = new NhanVienDAO();

    /**
     * Creates new form ChangePassForm
     */
    public ChangePassForm() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        txtNewPass = new swing.PasswordField();
        txtOldPass = new swing.TextField();
        txtConFirm = new swing.PasswordField();
        btnChange = new swing.Button();

        lblTitle1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(15, 69, 197));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Đổi mật khẩu");

        txtNewPass.setBackground(new java.awt.Color(245, 245, 245));
        txtNewPass.setLabelText("Mật khẩu mới");
        txtNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPassActionPerformed(evt);
            }
        });

        txtOldPass.setBackground(new java.awt.Color(245, 245, 245));
        txtOldPass.setLabelText("Mật khẩu cũ");
        txtOldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPassActionPerformed(evt);
            }
        });

        txtConFirm.setBackground(new java.awt.Color(245, 245, 245));
        txtConFirm.setLabelText("Nhập lại mật khẩu");
        txtConFirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConFirmActionPerformed(evt);
            }
        });

        btnChange.setBackground(new java.awt.Color(204, 204, 204));
        btnChange.setForeground(new java.awt.Color(0, 0, 0));
        btnChange.setText("Thay đổi");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtConFirm, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConFirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtOldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPassActionPerformed

    private void txtNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPassActionPerformed

    private void txtConFirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConFirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConFirmActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (txtOldPass.getText().trim().isEmpty()) {
            MsgBox.alert(mainFrame, "Chưa nhập mật khẩu cũ");
        } else if (txtNewPass.getText().trim().isEmpty()) {
            MsgBox.alert(mainFrame, "Chưa nhập mật khẩu mới");
            txtOldPass.setHelperText("");
        } else if (txtConFirm.getText().trim().isEmpty()) {
            MsgBox.alert(mainFrame, "Chưa xác nhận mật khẩu mới");
            txtNewPass.setHelperText("");
        } else {
            if (txtOldPass.getText().equalsIgnoreCase(Auth.user.getMatKhau())) {
                if (txtNewPass.getText().equalsIgnoreCase(txtConFirm.getText())) {
                    Auth.user.setMatKhau(txtNewPass.getText());
                    dao.update(Auth.user);
                    MsgBox.alert(mainFrame, "Đổi mật khẩu thành công!");
                    txtNewPass.setText("");
                    txtOldPass.setText("");
                    txtConFirm.setText("");
                } else {
                    MsgBox.alert(mainFrame, "Xác nhận mật khẩu sai");
                }
            }else{
                MsgBox.alert(mainFrame, "Mật khẩu cũ sai");
            }
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnChange;
    private javax.swing.JLabel lblTitle1;
    private swing.PasswordField txtConFirm;
    private swing.PasswordField txtNewPass;
    private swing.TextField txtOldPass;
    // End of variables declaration//GEN-END:variables
}
