/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import com.ReSys.dao.BanDAO;
import com.ReSys.dao.DanhMucDAO;
import com.ReSys.dao.HoaDonChiTietDAO;
import com.ReSys.dao.HoaDonDAO;
import com.ReSys.dao.MonAnDAO;
import com.ReSys.dao.ThongKeDAO;
import com.ReSys.entity.DanhMuc;
import com.ReSys.entity.HoaDon;
import com.ReSys.entity.HoaDonChiTiet;
import com.ReSys.entity.MonAn;
import com.ReSys.utis.Auth;
import com.ReSys.utis.DinhDang;
import com.ReSys.utis.JdbcHelper;
import com.ReSys.utis.MsgBox;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import transation.TransitionsForm;

/**
 *
 * @author HI
 */
public class DatBanForm extends TransitionsForm {

    private JButton[] nutBan;

    /**
     * Creates new form Form2
     */
    public DatBanForm() {
        initComponents();
        setOpaque(false);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnBan7 = new javax.swing.JButton();
        btnBan1 = new javax.swing.JButton();
        btnBan2 = new javax.swing.JButton();
        btnBan8 = new javax.swing.JButton();
        btnBan3 = new javax.swing.JButton();
        btnBan9 = new javax.swing.JButton();
        btnBan4 = new javax.swing.JButton();
        btnBan10 = new javax.swing.JButton();
        btnBan5 = new javax.swing.JButton();
        btnBan11 = new javax.swing.JButton();
        btnBan6 = new javax.swing.JButton();
        btnBan12 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhSachGoiMon = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboTenMon = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThemMon = new javax.swing.JButton();
        lblMaBan = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(102, 153, 255));

        btnBan7.setText("Bàn 7");
        btnBan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan7ActionPerformed(evt);
            }
        });

        btnBan1.setText("Bàn 1");
        btnBan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan1ActionPerformed(evt);
            }
        });

        btnBan2.setText("Bàn 2");
        btnBan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan2ActionPerformed(evt);
            }
        });

        btnBan8.setText("Bàn 8");
        btnBan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan8ActionPerformed(evt);
            }
        });

        btnBan3.setText("Bàn 3");
        btnBan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan3ActionPerformed(evt);
            }
        });

        btnBan9.setText("Bàn 9");
        btnBan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan9ActionPerformed(evt);
            }
        });

        btnBan4.setText("Bàn 4");
        btnBan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan4ActionPerformed(evt);
            }
        });

        btnBan10.setText("Bàn 10");
        btnBan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan10ActionPerformed(evt);
            }
        });

        btnBan5.setText("Bàn 5");
        btnBan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan5ActionPerformed(evt);
            }
        });

        btnBan11.setText("Bàn 11");
        btnBan11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan11ActionPerformed(evt);
            }
        });

        btnBan6.setText("Bàn 6");
        btnBan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan6ActionPerformed(evt);
            }
        });

        btnBan12.setText("Bàn 12");
        btnBan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBan7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Bàn", jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblDanhSachGoiMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaHDCT", "MaHD", "Tên Món", "Số Lượng", "Thành Tiền", "Ghi Chú"
            }
        ));
        jScrollPane3.setViewportView(tblDanhSachGoiMon);

        jLabel8.setText("Tổng Tiền");

        lblTongTien.setText("0.0");

        btnThanhToan.setBackground(new java.awt.Color(102, 204, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTongTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan)
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblTongTien))
                    .addComponent(btnThanhToan))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setText("Danh mục món");

        cboDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDanhMucActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên Món");

        cboTenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenMonActionPerformed(evt);
            }
        });

        txtSoLuong.setText("1");
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel4.setText("Số lượng");

        jLabel5.setText("Bàn");

        jLabel7.setText("Đơn giá");

        btnThemMon.setBackground(new java.awt.Color(102, 204, 255));
        btnThemMon.setText("Thêm Món");
        btnThemMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonActionPerformed(evt);
            }
        });

        lblMaBan.setText("0");

        lblDonGia.setText("0.0");

        jLabel3.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDonGia)
                                .addComponent(lblMaBan))
                            .addGap(218, 218, 218))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(btnThemMon)
                            .addGap(30, 30, 30)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cboDanhMuc, javax.swing.GroupLayout.Alignment.LEADING, 0, 234, Short.MAX_VALUE)
                        .addComponent(cboTenMon, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaBan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDonGia))
                .addGap(18, 18, 18)
                .addComponent(btnThemMon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        tabs.addTab("Đặt món", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnThemMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonActionPerformed
        // TODO add your handling code here:
        this.themHoaDon();

    }//GEN-LAST:event_btnThemMonActionPerformed

    private void btnBan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan1ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B01");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan1ActionPerformed

    private void btnBan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan2ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B02");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan2ActionPerformed

    private void btnBan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan3ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B03");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan3ActionPerformed

    private void btnBan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan4ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B04");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();

    }//GEN-LAST:event_btnBan4ActionPerformed

    private void btnBan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan5ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B05");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan5ActionPerformed

    private void btnBan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan6ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B06");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan6ActionPerformed

    private void btnBan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan7ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B07");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan7ActionPerformed

    private void btnBan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan8ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B08");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan8ActionPerformed

    private void btnBan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan9ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B09");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan9ActionPerformed

    private void btnBan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan10ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B10");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan10ActionPerformed

    private void btnBan11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan11ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B11");
        tabs.setSelectedIndex(1);
        this.tongTien();
    }//GEN-LAST:event_btnBan11ActionPerformed

    private void btnBan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan12ActionPerformed
        // TODO add your handling code here:
        lblMaBan.setText("B12");
        tabs.setSelectedIndex(1);
        this.fillTableHDCT();
        this.tongTien();
    }//GEN-LAST:event_btnBan12ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.deleteHDCT();

    }//GEN-LAST:event_btnXoaActionPerformed

    private void cboTenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenMonActionPerformed
        // TODO add your handling code here:
        this.fillDonGia();
    }//GEN-LAST:event_cboTenMonActionPerformed

    private void cboDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDanhMucActionPerformed
        // TODO add your handling code here:
        this.fillComboBoxMonAn();

    }//GEN-LAST:event_cboDanhMucActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        this.thanhToan();
    }//GEN-LAST:event_btnThanhToanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan1;
    private javax.swing.JButton btnBan10;
    private javax.swing.JButton btnBan11;
    private javax.swing.JButton btnBan12;
    private javax.swing.JButton btnBan2;
    private javax.swing.JButton btnBan3;
    private javax.swing.JButton btnBan4;
    private javax.swing.JButton btnBan5;
    private javax.swing.JButton btnBan6;
    private javax.swing.JButton btnBan7;
    private javax.swing.JButton btnBan8;
    private javax.swing.JButton btnBan9;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemMon;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboTenMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblMaBan;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDanhSachGoiMon;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
    BanDAO bandao = new BanDAO();
    DanhMucDAO dmdao = new DanhMucDAO();
    MonAnDAO madao = new MonAnDAO();
    ThongKeDAO tkdao = new ThongKeDAO();
    HoaDonDAO hddao = new HoaDonDAO();
    HoaDonChiTietDAO hdctdao = new HoaDonChiTietDAO();
    Date now = new Date();

    private void init() {
        danhSachBanNut();
        updateTableButtons();
        this.fillComboBoxDanhMuc();
        this.fillTableHDCT();
    }

    private int extractNumber(String maBan) {
        try {
            return Integer.parseInt(maBan.replaceAll("\\D", ""));
        } catch (NumberFormatException e) {
            e.printStackTrace();
            return -1; // Chỉ thị lỗi hoặc số không hợp lệ
        }
    }

    private void danhSachBanNut() {
        nutBan = new JButton[]{
            btnBan1, btnBan2, btnBan3, 
            btnBan4, btnBan5, btnBan6, 
            btnBan7, btnBan8, btnBan9, 
            btnBan10, btnBan11, btnBan12
        };
    }

    private boolean checkBanExists(String maBan) {
        String sql = "SELECT COUNT(*) FROM Ban WHERE MaBan = ?";
        try {
            ResultSet rs = JdbcHelper.query(sql, maBan);
            if (rs.next()) {
                int count = rs.getInt(1); 
                return count > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    public void updateTableButtons() {
        Map<String, Boolean> tableStatus = hddao.fetchTableStatus();
        for (Map.Entry<String, Boolean> entry : tableStatus.entrySet()) {
            String maBan = entry.getKey();
            boolean trangThai = entry.getValue();
            int tableId = extractNumber(maBan);
            if (maBan != null && tableId <= nutBan.length) {
                JButton button = nutBan[tableId - 1]; 
                if (!trangThai) {
                    button.setBackground(Color.decode("#ADD8E6"));
                }
            }

        }
    }

    private void fillComboBoxDanhMuc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDanhMuc.getModel();
        model.removeAllElements();
        List<DanhMuc> list = dmdao.selectAll();
        for (DanhMuc danhMuc : list) {
            model.addElement(danhMuc);
        }
        this.fillComboBoxMonAn();
    }

    private void fillComboBoxMonAn() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenMon.getModel();
        model.removeAllElements();
        DanhMuc dm = (DanhMuc) cboDanhMuc.getSelectedItem();
        if (dm != null) {
            List<MonAn> list = madao.selectByDanhMuc(dm.getMaDM());
            for (MonAn mon : list) {
                model.addElement(mon);
            }
            this.fillDonGia();
        }
    }

    private void fillDonGia() {
        MonAn mon = (MonAn) cboTenMon.getSelectedItem();
        if (mon != null) {
//            String formatDonGia = String.format("%,.0f", mon.getDonGia()) + " VND";
//            lblDonGia.setText(String.valueOf(formatDonGia));
              lblDonGia.setText(DinhDang.formatCurrency(mon.getDonGia())+" VND");
        } else {
            lblDonGia.setText("");
        }
    }

    public void fillTableHDCT() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachGoiMon.getModel();
        model.setRowCount(0);
        String ban = lblMaBan.getText();
        if (ban != null) {
            List<Object[]> list = tkdao.getHDCT(ban);
            for (Object[] row : list) {
                model.addRow(row);
            }
        }
    }

    private HoaDon getFormHD() {
        HoaDon hd = new HoaDon();
        hd.setMaBan(lblMaBan.getText());
        hd.setMaNV(Auth.user.getMaNV());
        hd.setNgayGio(new Date());
        hd.setTrangThai(false);
        return hd;
    }

//    private boolean checkForm() {
//        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
//        if (lblMaBan.getText().equals("0") || txtSoLuong.getText().isEmpty()) {
//            MsgBox.alert(mainFrame, "Thông tin bàn hoặc số lượng món chưa được chọn!");
//            return false;
//        } else {
//            return true;
//        }
//    }
    private boolean checkForm() {
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        String maBan = lblMaBan.getText();
        String soLuong = txtSoLuong.getText();
        if (maBan.equals("0")) {
            MsgBox.alert(mainFrame, "Bạn chưa chọn bàn để thêm món!");
            return false;
        } else if (!checkBanExists(maBan)) {
            MsgBox.alert(mainFrame, "Bàn này không tồn tại trong hệ thống.");
            return false;
        } else if (soLuong.isEmpty()) {
            MsgBox.alert(mainFrame, "Số lượng món không được bỏ trống!");
            return false;
        } else {
            return true;
        }
    }


    private void themHoaDon() {
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (checkForm()) {
            String maBan = lblMaBan.getText();
            List<HoaDon> list = hddao.selectHoaDonChuatt(maBan);
            if (list != null) {
                for (HoaDon hd : list) {
                    int maHD = hd.getMaHD();
                    this.themHDCT(maHD);
                    MsgBox.alert(mainFrame, "Thêm mới hóa đơn chi tiết thành công!");
                }
            } else {
                HoaDon hd = getFormHD();
                try {
                    hddao.insert(hd);
                    int maHD = hddao.selectMaHDNew();
                    this.themHDCT(maHD);
                    MsgBox.alert(mainFrame, "Thêm mới hóa đơn,Hóa đơn chi tiết thành công!");
                } catch (Exception e) {
                    e.printStackTrace();
                    MsgBox.alert(mainFrame, "Thêm mới hóa đơn thất bại!");
                }

            }
        }
    }

    private HoaDonChiTiet getFormHDCT(int maHD) {
        HoaDonChiTiet hdct = new HoaDonChiTiet();
        MonAn mon = (MonAn) cboTenMon.getSelectedItem();
        hdct.setMaHD(maHD);
        hdct.setMaMon(mon.getMaMon());
        hdct.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        hdct.setGhiChu(txtGhiChu.getText());
        return hdct;
    }

    private void themHDCT(int maHD) {
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        HoaDonChiTiet hdct = getFormHDCT(maHD);
        try {
            hdctdao.insert(hdct);
            this.fillTableHDCT();
            this.tongTien();
            this.updateTableButtons();
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(mainFrame, "Thêm mới hóa đơn chi tiết thất bại!");
        }
    }

    private void update() {
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        int rowCount = tblDanhSachGoiMon.getRowCount();

        if (rowCount > 0) {
            try {
                for (int row = 0; row < rowCount; row++) {
                    int maHDCT = (int) tblDanhSachGoiMon.getValueAt(row, 0);
                    Object value = tblDanhSachGoiMon.getValueAt(row, 3);
                    int soLuong = 0;
                    if (value instanceof Integer) {
                        soLuong = (Integer) value;
                    } else if (value instanceof String) {
                        soLuong = Integer.parseInt((String) value);
                    } else if (value instanceof Double) {
                        soLuong = ((Double) value).intValue();
                    }
                    System.out.print(soLuong);
                    String ghiChu = (String) tblDanhSachGoiMon.getValueAt(row, 5);
                    HoaDonChiTiet hdct = hdctdao.selectByma(maHDCT);
                    hdct.setSoLuong(soLuong);
                    hdct.setGhiChu(ghiChu);
                    hdctdao.update(hdct);
                }
                this.fillTableHDCT();
                this.tongTien();
                this.updateTableButtons();
                MsgBox.alert(mainFrame, "Cập nhật thông tin hóa đơn chi tiết thành công!");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(mainFrame, "Cập nhật thông tin hóa đơn chi tiết thất bại!");
            }
        } else {
            MsgBox.alert(mainFrame, "Chưa có thông tin để cập nhật!");
        }
    }

    private void deleteHDCT() {
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (tblDanhSachGoiMon.getRowCount() > 0) {
            int Row = tblDanhSachGoiMon.getSelectedRow();
            if (Row >= 0) {
                int maHDCT = (int) tblDanhSachGoiMon.getValueAt(Row, 0);
                int maHD = (int) tblDanhSachGoiMon.getValueAt(Row, 1);
                try {
                    hdctdao.delete(String.valueOf(maHDCT));

                    if (hdctdao.countByMaHD(maHD) == 0) {
                        hddao.delete(String.valueOf(maHD));
                        this.updateTableButtons();
                        MsgBox.alert(mainFrame, "Xóa hóa đơn và tất cả chi tiết thành công!");
                    } else {
                        MsgBox.alert(mainFrame, "Xóa hóa đơn chi tiết thành công!");
                    }
                    this.fillTableHDCT();
                    this.tongTien();
                } catch (Exception e) {
                    e.printStackTrace();
                    MsgBox.alert(mainFrame, "Xóa hóa đơn chi tiết thất bại!");
                }
            } else {
                MsgBox.alert(mainFrame, "Chọn một hàng để xóa!");
            }
        } else {
            MsgBox.alert(mainFrame, "Chưa có món để xóa!");
        }

    }

    private double tongTien() {
        double tongTien = 0;
        for (int i = 0; i < tblDanhSachGoiMon.getRowCount(); i++) {
            double tien = (double) tblDanhSachGoiMon.getValueAt(i, 4);
            tongTien += tien;
        }
//        String formattedTongTien = String.format("%,.0f", tongTien) + " VND";
//        lblTongTien.setText(formattedTongTien);
          lblTongTien.setText(DinhDang.formatCurrency(tongTien)+" VND");
        return tongTien;
    }

    private void thanhToan() {
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (tblDanhSachGoiMon.getRowCount() > 0) {
            int mahd = (int) tblDanhSachGoiMon.getValueAt(0, 1);
            double tongTien=tongTien();
            String maBan=lblMaBan.getText();
            tabs.setSelectedIndex(0);
            new PhieuThanhToanForm(mahd,tongTien,maBan).setVisible(true);
        } else {
            MsgBox.alert(mainFrame, "Chưa có món để thanh toán!");
        }
    }
}
